---
title: 'Fontes: CliometricsBR'
author: "Luiz Paulo T. Gonçalves"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exportações: 

**Exportações brasileiras de açúcar: quantidade**

Frequência: Anual 

Fonte: IPEAdata

Unidade: Tonelada

Comentário: As exportações são os valores das vendas para o exterior e outras remessas de bens de propriedade de residentes no país, registrado na Balança Comercial do Balanço de Pagamentos.Neste caso, trata-se da quantidade exportada de açúcar pelo Brasil. Fontes: A partir de 1988: Ministério do Desenvolvimento, Indústria e Comércio Exterior, Secretaria de Comércio Exterior (MDIC/Secex). Para 1821-1987: Estatísticas históricas do Brasil: séries econômicas, demográficas e sociais de 1550 a 1988. 2. ed. rev. e atual. do v. 3 de Séries estatísticas retrospectivas. Rio de Janeiro: IBGE, 1990. Apud: Estatísticas do século XX, Centro de documentação e disseminação de informações. Rio de Janeiro: IBGE, 2003. Nota: Os dados referem-se ao açúcar cristal, demerara, mascavo e branco e, de 1942 a 1987, também ao refinado. No período de 1833 a 1887: os dados referem-se ao ano fiscal (de julho do ano anterior a junho do ano de referência). Mais Informações: Sistema de Contas Nacionais, 2010, 3ª edição - IBGE. 
Atualizado em: 29/04/2020

